alta:
  version: 1.0

spring:
  datasource:
    url: jdbc:mysql://10.10.40.253:3306/test?useServerPrepStmts=true&cachePrepStmts=true&setUnicode=true&characterEncoding=UTF-8&autoReconnectForPools=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 3
  redis:
    database: 7
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 100
        max-wait: -1s
        max-idle: 20
        min-idle: 5
    timeout: 2000ms